fixed usage of use_nominal_extrinsics parameter
realsenseai/realsense-ros pull request #1204
Opened 2020-05-18 08:44 UTC by procopiostein

this parameter was being incorrectly parsed.
its value was not taken into account in each device's xacro.

this PR fixed the parameter usage and update the tests to use it properly.

2020-05-18 14:50 UTC, saikishor commented
:+1: 
Nice fix! Looks good to me!

2020-05-18 14:51 UTC, saikishor approved these changes
+1
Nice fix! Looks good to me!

2020-05-18 15:31 UTC, saikishor requested changes
@procopiostein can you change `${arg use_nominal_extrinsics}` by `$(arg use_nominal_extrinsics)`

2020-05-18 20:52 UTC, mcamurri commented
Isn't this the same as #1125 ?

2020-05-19 07:58 UTC, procopiostein commented
@mcamurri not only it is the same but yours is much better documented and ready to merge. thanks, I'll close this.

2020-05-19 07:58 UTC, closed without merging