Add: ros noetic branch with cpp 14 CMake
realsenseai/realsense-ros pull request #1450
Opened 2020-10-15 19:12 UTC by Darkproduct

We succeeded with building this on noetic with the `lagacy` branch on [librealsense](https://github.com/IntelRealSense/librealsense). We suggest to merge this or create a new branch.

2020-11-19 12:31 UTC, doronhi commented
I tested using -std=c++11 on Noetic (focal) and merged #1474 . Is there a reason to switch to -std=c++14?

2020-11-19 19:26 UTC, Darkproduct commented
We have a Intel RealSense R200, which is no longer supported by version 2.0 on [librealsense](https://github.com/IntelRealSense/librealsense). But with the `legacy branch` from [librealsense](https://github.com/IntelRealSense/librealsense) the R200 still works. 

For this setup, I created a new branch from `IntelRealSense:indigo-devel` called `noetic-devel`. The change to `-std=c++14` fixed all the compiler errors.

Therefore I created this merge request to merge to `indigo-devel` and not to the `development` branch, because we needed to support the older version on ros-noetic.

2020-11-22 09:08 UTC, doronhi commented
Thanks for clarifying the context for me. I think I rather have 1 unmaintained branch in the repository than a couple as I fear a branch called noetic-devel will confuse users. If the same version works on indigo and noetic, I'd rather rename indigo-devel branch to legacy-devel branch and use some phrase like this (didn't test it - could have syntax issues...):
```
if [[ $(lsb_release -sc) == "focal" ]]; then _cpp_compiler=c++14;
else _cpp_compiler=c++11;
fi
```
What do you think?

2021-02-25 18:20 UTC, Darkproduct commented
Sounds good to me. Then the `legacy` branch from [librealsense](https://github.com/IntelRealSense/librealsense) will be compatible to this new `legacy` branch here. It would be nice, if you can point this out somewhere. Additionally, the `legacy` branch wouldn't suggest to not be compatible to newer ros versions. We use ros melodic and noetic and haven't had issues so far.

2021-02-28 05:16 UTC, doronhi commented on realsense_camera/CMakeLists.txt
>  # Flags executables
The compiler should be selected according to the OS version.

2021-02-28 05:17 UTC, doronhi requested changes
Based on our discussion, the compiler should be selected with something of the form:
if [[ $(lsb_release -sc) == "focal" ]]; then _cpp_compiler=c++14;
else _cpp_compiler=c++11;
fi

2023-01-25 09:50 UTC, Nir-Az commented
We will close this PR as won't do as we no longer developing ROS1.

Thanks for your effort.

2023-01-25 09:50 UTC, closed without merging