IR stream enable
realsenseai/realsense-ros pull request #150
Opened 2016-11-14 18:21 UTC by mkhansen-intel

**Please ensure the above *guidelines for contributing* are met.**

Fixes Issue: #

Changes proposed in this pull request:
- Adds enable parameters for IR and IR2 streams
- Adds new RVIZ files for use with default and RGBD launch files
-

2016-11-14 19:17 UTC, mdhorn requested changes
A few minor changes needed.

2016-11-14 19:17 UTC, mdhorn commented on realsense_camera/src/r200_nodelet.cpp
> +    else if (enable_[RS_STREAM_INFRARED] == false)
Should this be RS_STEAM_INFRARED2?

2016-11-14 19:17 UTC, mdhorn commented on realsense_camera/launch/r200_nodelet_modify_params.launch
> +  <arg name="enable_ir"         default="true" />
Should these default to False?

2016-11-14 19:17 UTC, mdhorn commented on realsense_camera/launch/r200_nodelet_modify_params.launch
> +  <arg name="enable_ir"         default="true" />
These probably need to be added to the nodelet_rgbd.launch.xml file as well.

2016-11-15 01:56 UTC, mdhorn approved these changes
👍

2016-11-15 20:39 UTC, reaganlo approved these changes
Approved :+1:

2016-11-15 23:13 UTC, merged