Upload 18 BAT tests
realsenseai/realsense-ros pull request #193
Opened 2017-01-17 01:21 UTC by wangji1

Upload first version of stable bat tests, there are 2 common tests
to check librealsense and realsense_camera installed, and there are
4 specific tests of each camera (R200/F200/SR300/ZR300) to check
camera info matrix, enabled tf, set power off/on and force power
off/on, totally 18 tests.

All the tests are based on rospy, using python script as test type.

**Please ensure the above *guidelines for contributing* are met.**

Fixes Issue: #

Changes proposed in this pull request:
-
-
-

2017-01-23 23:15 UTC, mdhorn requested changes

2017-01-23 23:15 UTC, mdhorn commented on realsense_camera/CMakeLists.txt
> +    rm -rf ${SCRIPT_DIR}/scripts
Why is this needed?
I'm not exciting about having an `rm -rf` in the build flow.

2017-01-24 01:46 UTC, mdhorn commented
As we are adding new Python scripts to the repository, please enable roslint for Python and ensure it is passing.

```
diff --git a/realsense_camera/CMakeLists.txt b/realsense_camera/CMakeLists.txt
index 77d5e909b801..1d3fb979ada4 100644
--- a/realsense_camera/CMakeLists.txt
+++ b/realsense_camera/CMakeLists.txt
@@ -59,6 +59,7 @@ generate_dynamic_reconfigure_options(
 
 # ROS Lint the code
 roslint_cpp()
+roslint_python()
 roslint_add_test()
 
 #################################

```

And use this command to run roslint:
`catkin_make roslint`

2017-01-24 02:50 UTC, wangji1 commented on realsense_camera/CMakeLists.txt
> +    rm -rf ${SCRIPT_DIR}/scripts
I want to remove the copied scripts when user clean the building environment, but not find how to remove it when run "catkin_make clean". so I add a customer target to remove them.
What it the correct method?

2017-02-23 02:10 UTC, wangji1 commented
I have updated python scripts, and they are passed catkin_make roslint.
@mdhorn  I'm not sure will you still want to merge this PR to RS camera project?
If yes, please help to review again.
If not, please close it directly.

Thanks!

2017-02-23 19:39 UTC, mdhorn approved these changes

2017-02-23 19:39 UTC, merged