Sync f200 sr300
realsenseai/realsense-ros pull request #209
Opened 2017-03-03 21:37 UTC by mkhansen-intel

**Please ensure the above *guidelines for contributing* are met.**

Fixes Issue: #

Changes proposed in this pull request:
- Adds new synchronous base class which uses rs_wait_for_frames for use with the F200 & SR300 cameras, this is to improve the reliability when running RGBD, which relies on synchronous color & depth streams
-
-

2017-03-08 23:37 UTC, mdhorn requested changes

2017-03-08 23:37 UTC, mdhorn commented on realsense_camera/src/sync_nodelet.cpp
> +
Please add a destructor for this class which does the thread join for the topic_thread_

topic_thread_->join();

2017-03-08 23:37 UTC, mdhorn commented on realsense_camera/src/sync_nodelet.cpp
> +        start_stop_srv_called_ = false;
please add a blank line

2017-03-08 23:37 UTC, mdhorn commented on realsense_camera/src/sync_nodelet.cpp
> +          if (camera_publisher_[RS_STREAM_COLOR].getNumSubscribers() <= 0)
please add a blank line

2017-03-08 23:37 UTC, mdhorn commented on realsense_camera/src/sync_nodelet.cpp
> +          publishPCTopic();
please add a blank line

2017-03-08 23:37 UTC, mdhorn commented on realsense_camera/src/sync_nodelet.cpp
> +      ts_[stream_index] = frame_ts;
please add a blank line

2017-03-08 23:37 UTC, mdhorn commented on realsense_camera/src/sync_nodelet.cpp
> +  void SyncNodelet::setImageData(rs_stream stream_index)
please add a blank line

2017-03-09 00:32 UTC, mdhorn approved these changes
LGTM 👍

2017-03-20 19:06 UTC, mattcurfman reviewed
Looks good, thank you.

2017-03-20 19:07 UTC, mattcurfman approved these changes

2017-03-20 23:25 UTC, merged