Dynamic reconfigure of SR300 exposure controls
realsenseai/realsense-ros pull request #214
Opened 2017-03-08 00:35 UTC by jamessergeant

**Please ensure the above *guidelines for contributing* are met.**

Fixes Issue: #213 

Changes proposed in this pull request:
- Addition of dynamic_reconfigure parameters color_exposure and color_enable_auto_exposure with appropriate default, min and max values as specified by librealsense cpp-enumerated-devices output for the SR300
- RS_OPTION_COLOR_ENABLE_AUTO_EXPOSURE and RS_OPTION_COLOR_EXPOSURE setting in SR300Nodelet::configCallback based on white balance method.

Tested on following system:
```
| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | Ubuntu 14.04.5 LTS   |
| Kernel                | 4.4.0-64-generic     |
| ROS                   | indigo               |
| ROS RealSense         | 1.7.1                |
| librealsense          | 1.12.1               |
| Camera Type-Firmware  | 3.17.0.0             |
```

2017-03-16 02:10 UTC, jamessergeant commented
Any feedback on this at all?

2017-03-16 20:55 UTC, mdhorn requested changes
Sorry, we were in the middle of a regression which needed to be completed before merging new code.

Looks good to me, but please update the Copyright date on line 2 of sr300_nodelet.cpp to be the year 2017.

2017-03-16 22:03 UTC, mdhorn requested changes
This same change is also missing for the R200 and F200 camera. Can we update this PR to make the same addition for all of the cameras?

2017-03-20 23:44 UTC, mdhorn commented
We are planning a release candidate for our QA team by Thursday. We will need to get the changes completed soon to make this next release.

@jamessergeant If you do not want to make the changes for other cameras, or do not have the time, just let me know.
I'll grab your PR, make the changes, and submit a replacement PR -- I'll still list you as the author.

2017-03-20 23:48 UTC, jamessergeant commented
Sorry @mdhorn have been away from github given a looming assessment. I will the copyright date now. I will also make the changes to the other cameras, following the same process as I have for SR300 however do not have ready access to test these. Will commit the changes shortly.

2017-03-20 23:58 UTC, jamessergeant commented
@mdhorn updated. As per previous, haven't been able to test the F200 and R200.

2017-03-21 00:03 UTC, mdhorn commented
@jamessergeant Thank you for the updates.
I'll validate the changes on R200 and F200 before merging.

2017-03-21 23:26 UTC, mdhorn commented
@jamessergeant Basic testing shows auto exposure for color working on F200 and R200.
Thank you.

2017-03-21 23:26 UTC, mdhorn approved these changes

2017-03-21 23:29 UTC, merged