Enable configuration of the TF publication rate when using tf_dynamic
realsenseai/realsense-ros pull request #221
Opened 2017-03-24 14:31 UTC by severin-lemaignan

The parameter is called `tf_publication_rate`

Related to review comment on issue #169

2017-03-24 18:54 UTC, mdhorn commented
Add my same comment here for clarity:

The data is not changing, hence the slow loop rate.

The default for transforms is to publish them with a static transform, but due to a ROS bug (and a camera driver bug for F200/SR300) the dynamic transform option was added.
See http://wiki.ros.org/realsense_camera#Transform_Restrictions

2017-03-24 19:50 UTC, severin-lemaignan commented
@mdhorn I'm using `enable_tf_dynamic` exactly for the reason described in #169 (which is indeed even more acute for F200/SR300 as I do not have to option to use 2 launch files).

That said, dynamically publishing the transform at 1Hz is essentially useless: TF will be usually unable to compute transforms between the camera frames and other frames in the system as the camera transforms will be too old.

For instance, in the old [tf#static_transform_publisher](http://wiki.ros.org/tf#static_transform_publisher) (ie, before tf2 and the latched `/tf_static` topic), they recommend 10Hz.

2017-03-24 21:42 UTC, mdhorn requested changes

2017-03-24 21:42 UTC, mdhorn commented on realsense_camera/launch/r200_nodelet_modify_params.launch
> +  <arg name="tf_publication_rate" default="1.0" />
This file is missing setting the parameter with the argument value.
Around line 34, the following should be added:
```
  <param name="$(arg camera)/driver/tf_publication_rate" type="double" value="$(arg tf_publication_rate)" />
```

2017-03-24 23:40 UTC, severin-lemaignan commented on realsense_camera/launch/r200_nodelet_modify_params.launch
> +  <arg name="tf_publication_rate" default="1.0" />
My bad. Fixed.

2017-03-24 23:58 UTC, mdhorn approved these changes

2017-03-25 00:00 UTC, mdhorn commented
@severin-lemaignan We just started a validation cycle for the release of 1.8.0.
I'll check with our QA team, and if they to adding this change and still keep our scheduled I'll merge this on Monday; else it may be a week before merging.

2017-03-27 22:55 UTC, merged